[package]
name = "gitm"
version = "0.1.0"
authors = ["Arsen Musayelyan <arsen@arsenm.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
serde_derive = "1.0"
serde = "1.0"
log = "0.4"
env_logger = "0.8"